# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  firmware:
    cmds:
      - docker-compose -f docker-compose-firmware-build.yml {{.CLI_ARGS}}
  
  fw-up:
    cmds:
      - docker-compose -f docker-compose-firmware-build.yml up -d klipper-firmware

  fw-build:
    cmds:
      - docker-compose -f docker-compose-firmware-build.yml build klipper-firmware
  
  fw-exec:
    cmds:
      - docker-compose -f docker-compose-firmware-build.yml exec klipper-firmware bash
   