# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  firmware:
    cmds:
      - docker-compose -f docker-compose-firmware-build.yml {{.CLI_ARGS}} 